trigger:
- main

pool:
    vmImage: ubuntu-latest

variables:
    bildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
